project:
  type: website

website:
  title: "Satici Lab"
  open-graph:
    description: "Research website for the Satici Lab"
    site-name: Satici Lab
  navbar:
    logo: /images/monogram_solid-blk.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - research.qmd
      - publications.qmd
      - teaching.qmd
      - text: "People"
        href: people/index.qmd
        id: "people-sidebar"
      - text: "Positions"
        href: positions/index.qmd
      - text: "More"
        menu:
          - about.qmd
          - chiasson.qmd
    right:
      - icon: github
        text: Github
        href: https://github.com/symplectomorphism
      
  sidebar:
    - id: "people-sidebar"
      title: "People"
      style: "docked"
      contents:
        - people/index.qmd
        - text: "Aykut C. Satici"
          href: people/aykut.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "Currently looking for PhD students on robotics, control, and machine learning! Please see the [positions](/positions/index.qmd) tab."
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    light: flatly
    dark: darkly
    toggle: true
    respect-user-color-scheme: true
