project:
  type: website

website:
  title: "Satici Lab"
  page-navigation: true
  open-graph:
    description: "Research website for the Satici Lab"
    site-name: Satici Lab
  navbar:
    logo: /images/monogram_solid-blk.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
        id: "research-sidebar"
      - publications.qmd
      - text: "Teaching"
        href: teaching/index.qmd
        id: "teaching-sidebar"
      - text: "People"
        href: people/index.qmd
        id: "people-sidebar"
      - text: "Positions"
        href: positions/index.qmd
      - text: "More"
        menu:
          - about.qmd
          - text: "John Chiasson"
            href: chiasson/index.qmd
            id: "chiasson-sidebar"
    right:
      - icon: github
        text: Github
        href: https://github.com/symplectomorphism
      
  sidebar:
    - id: "people-sidebar"
      title: "People"
      style: "docked"
      contents:
        - people/index.qmd
        - text: "Aykut C. Satici"
          href: people/aykut.qmd
        - section: "Current Members"
          contents:
            - text: "Graduate Students"
              href: people/graduate_students.qmd
            - text: "Undergraduate Students"
              href: people/undergraduate_students.qmd
        - section: "Alumni"
          contents:
            - text: "Graduate Students"
              href: people/alumni_graduate_students.qmd
            - text: "Undergraduate Students"
              href: people/alumni_undergraduate_students.qmd
    - id: "research-sidebar"
      title: "Research"
      style: "docked"
      contents:
        - research/index.qmd
        - text: "Robotics and Control"
          href: research/robotics_and_control.qmd
        - text: "Robust Machine Learning"
          href: research/robust_machine_learning.qmd
    - id: "teaching-sidebar"
      title: "Teaching"
      collapse-level: 2
      style: "docked"
      scope: "teaching/"
      contents:
        - teaching/index.qmd
        - section: "Graduate Courses"
          contents:
            - text: "Robotics"
              href: teaching/robotics.qmd
            - text: "Optimization"
              href: teaching/optimization.qmd
            - section: "Deep Learning"
              file: teaching/grad_courses/deep_learning/index.qmd
              contents:
                - text: "Basics of Optimization"
                  href: teaching/grad_courses/deep_learning/week01.qmd
                - text: "Intro to Neural Nets"
                  href: teaching/grad_courses/deep_learning/week02.qmd
        - section: "Undergraduate Courses"
          contents:
            - text: "Kinematics and Machine Dynamics"
              href: teaching/kinematics_and_dynamics_machines.qmd
            - text: "System Modeling and Control"
              href: teaching/smac.qmd
            - text: "Mechatronics"
              href: teaching/mechatronics.qmd
    - id: "chiasson-sidebar"
      title: "John Chiasson"
      style: "docked"
      contents:
        - chiasson/index.qmd
        - text: "Blog"
          href: chiasson/blog.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "Currently looking for PhD students on robotics, control, and machine learning! Please see the [positions](/positions/index.qmd) tab."
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    light: flatly
    dark: darkly
    toggle: true
    respect-user-color-scheme: true
    include-before-body: _math_macros.qmd
    html-math-method: mathjax
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          loader: {
            load: ['[tex]/boldsymbol', '[tex]/mathtools']
          },
          tex: {
            packages: {'[+]': ['boldsymbol', 'mathtools']}
          }
        };
        </script>