project:
  type: website

website:
  title: "Satici Lab"
  open-graph:
    description: "Research website for the Satici Lab"
    site-name: Satici Lab
  navbar:
    logo: /images/monogram_solid-blk.png
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - people.qmd
      - positions.qmd
      - text: "More"
        menu:
          - about.qmd
          - chiasson.qmd
    right:
      - icon: github
        text: Github
        href: https://github.com/symplectomorphism

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this is some information that you should pay attention to"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    light: flatly
    dark: darkly
    toggle: true
    respect-user-color-scheme: true
